aliases:
  champion: '2'
creation_timestamp: 1784041941935
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1784258757904
name: diabetes-risk-model-v3
workspace: default
