stages:
  fetch_data:
    cmd: python src/diabetes_risk_prediction/components/data_ingestion.py
    outs:
      - data/raw/raw_data.csv

  train:
    cmd: python src/diabetes_risk_prediction/components/model_trainer.py
    deps:
      - data/raw/raw_data.csv
      - src/diabetes_risk_prediction/components/model_trainer.py
    params:
      - train.test_size
      - train.random_state
      - train.n_trials
      - train.cv_folds
      - train.target_metric
      - mlflow.experiment_name
      - mlflow.tracking_uri
      - mlflow.registered_model_name
    outs:
      - artifacts/model_trainer/model.pkl
    metrics:
      - artifacts/metrics.json:
          cache: false
    plots:
      - artifacts/confusion_matrix.json:
          cache: false
          template: confusion
          x: predicted
          y: actual