stages:
  train_pipeline:
    cmd: python src/diabetes_risk_prediction/pipeline/training_pipeline.py
    deps:
      - data/raw/raw_data.csv
      - src
      - config/params.yaml
    params:
      - config/params.yaml
    outs:
      - artifacts
    metrics:
      - artifacts/metrics.json:
          cache: false
    plots:
      - artifacts/confusion_matrix.json:
          cache: false
          template: confusion
          x: predicted
          y: actual