apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-api
  labels:
    app: diabetes-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: diabetes-api

  template:
    metadata:
      labels:
        app: diabetes-api

    spec:

      imagePullSecrets:
        - name: ecr-pull-secret

      containers:

        - name: diabetes-api

          image: 146637284455.dkr.ecr.us-east-1.amazonaws.com/diabetes-app:v1.0.0

          imagePullPolicy: Always

          ports:
            - containerPort: 8000


          env:

            # Application reads model from MLflow registry
            - name: MODEL_SOURCE
              value: "mlflow"


            # MLflow inside cluster
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.mlflow.svc.cluster.local:5000"


            - name: MLFLOW_MODEL_NAME
              value: "diabetes-risk-model"


            - name: MLFLOW_MODEL_STAGE
              value: "Production"


          resources:

            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"



          readinessProbe:

            httpGet:

              path: /health

              port: 8000

            initialDelaySeconds: 15

            periodSeconds: 10



          livenessProbe:

            httpGet:

              path: /health

              port: 8000

            initialDelaySeconds: 30

            periodSeconds: 20