apiVersion: apps/v1
kind: Deployment

metadata:
  name: diabetes-api
  namespace: diabetes-prod

  # annotations:
  #   deployment.kubernetes.io/revision: "${IMAGE_TAG}"

  labels:
    app: diabetes-api

spec:
  revisionHistoryLimit: 3
  replicas: 1

  selector:
    matchLabels:
      app: diabetes-api

  strategy:
    type: RollingUpdate
    
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: diabetes-api

    spec:
      imagePullSecrets:
        - name: ecr-pull-secret

      containers:
        - name: diabetes-api
          image: placeholder
          # # image: 146637284455.dkr.ecr.us-east-1.amazonaws.com/db-risk-app:v7
          # image: ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/ECR_REPO:v7
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: MODEL_SOURCE
              value: "mlflow"

          envFrom:
            - configMapRef:
                name: diabetes-config

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true

      restartPolicy: Always
