apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data-pvc
  namespace: mlflow
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: python:3.11-slim
          command:
            - sh
            - -c
            - |
              pip install --no-cache-dir mlflow==2.17.0 && \
              mlflow server \
                --backend-store-uri sqlite:////mlflow-data/mlflow.db \
                --default-artifact-root /mlflow-data/artifacts \
                --host 0.0.0.0 \
                --port 5000 \
                --workers 1
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 6
            
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow-data
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
            

      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
