artifact_uri: file:///F:/_DataScienc_KNaik/NEW_GIT_PROJECT_DS/MLOPS_FASTAPI_GKE/mlops-fastapi-docker-gke/${MLFLOW_TRACKING_URI}/952619489996668971/cafc67bd85fe40618f6561f784c8a202/artifacts
end_time: 1784041769312
entry_point_name: ''
experiment_id: '952619489996668971'
lifecycle_stage: active
run_id: cafc67bd85fe40618f6561f784c8a202
run_name: nervous-foal-117
run_uuid: cafc67bd85fe40618f6561f784c8a202
source_name: ''
source_type: 4
source_version: ''
start_time: 1784041769064
status: 3
tags: []
user_id: rohit
