artifact_uri: file:///F:/_DataScienc_KNaik/NEW_GIT_PROJECT_DS/MLOPS_FASTAPI_GKE/mlops-fastapi-docker-gke/${MLFLOW_TRACKING_URI}/952619489996668971/f4bc4d34f6ae4c5091ae559e3ae872d8/artifacts
end_time: 1784041061682
entry_point_name: ''
experiment_id: '952619489996668971'
lifecycle_stage: active
run_id: f4bc4d34f6ae4c5091ae559e3ae872d8
run_name: nervous-pug-657
run_uuid: f4bc4d34f6ae4c5091ae559e3ae872d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1784041061513
status: 3
tags: []
user_id: rohit
