artifact_uri: file:///F:/_DataScienc_KNaik/NEW_GIT_PROJECT_DS/MLOPS_FASTAPI_GKE/mlops-fastapi-docker-gke/${MLFLOW_TRACKING_URI}/952619489996668971/d1df38dc8ab641aea08dab91f76b8d8c/artifacts
end_time: 1784041093713
entry_point_name: ''
experiment_id: '952619489996668971'
lifecycle_stage: active
run_id: d1df38dc8ab641aea08dab91f76b8d8c
run_name: incongruous-asp-157
run_uuid: d1df38dc8ab641aea08dab91f76b8d8c
source_name: ''
source_type: 4
source_version: ''
start_time: 1784041093544
status: 3
tags: []
user_id: rohit
